version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: superapp_postgres
    restart: always
    environment:
      POSTGRES_USER: superapp
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: superappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: superapp_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: superapp_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    command: npm run dev
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: superapp_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

