version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: superapp_backend
    env_file:
      - ./backend/.env.production
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: superapp_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: superapp_nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

  postgres:
    image: postgres:15
    container_name: superapp_postgres
    restart: always
    environment:
      POSTGRES_USER: superapp
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: superapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: superapp_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

